Repository pyupio/safety, pull requests merged in 2020-03, with the labels that each got.

#248 resolve false negatives due to hashes in requirements file
  safety/util.py
  tests/test_safety.py
Labels: approved

#220 added gitlab-ci.yml instructions to README CI help
  README.md
Labels: approved

#226 Fix error message for invalid API Key from environment variable
  safety/cli.py
Labels: approved

#289 Fix -r inside requirements.txt files (#132)
  safety/util.py
  tests/reqs_1.txt
  tests/reqs_2.txt
  tests/reqs_3.txt
  tests/test_safety.py
Labels: approved, bug

#293 Use safe ASCII art characters with sheet report (closes #119)
  .travis.yml
  README.md
  appveyor.yml
  safety/formatter.py
  tests/test_safety.py
Labels: bug
