Repository pyupio/safety, pull requests merged in 2025-05, with the labels that each got.

#729 fix: uv index out of range issue
  safety/tool/uv/command.py
Labels: bug

#730 Added resolution of installed packages
  .safety-project.ini
  safety/tool/pip/command.py
Labels: enhancement

#731 fix: suppress event loop errors during subprocess transport cleanup
  safety/asyncio_patch.py
  safety/tool/tool_inspector.py
Labels: bug

#732 chore:improved rendering of the warning messages
  safety/tool/pip/command.py
Labels: enhancement

#733 fix: usage of aot instead of tables for uv project
  safety/tool/uv/main.py
  tests/tool/uv/test_main.py
Labels: bug

#734 fix: missing uninstall option when feature flag is disabled
  safety/cli_util.py
Labels: bug

#735 bug: fix the version information passing
  safety/tool/pip/command.py
Labels: bug

#737 feat: add 'SAFETY_REQUEST_TIMEOUT_EVENTS' so users can use a custom timeout
  safety/events/handlers/common.py
Labels: enhancement

#739 fix: poetry error on source and parsing pyproject.toml
  safety/tool/base.py
  safety/tool/poetry/command.py
  safety/tool/poetry/constants.py
  safety/tool/poetry/main.py
  safety/tool/poetry/parser.py
Labels: bug

#749 fix: click version constraint
  pyproject.toml
Labels: enhancement

#747 ci: make sure tests run if lint is skipped
  .github/workflows/ci.yml
Labels: bug

#750 ci: avoid lint on schedule but keep matrix/tests
  .github/workflows/ci.yml
Labels: bug, enhancement

#751 fix: add missing uv index env var for auth
  safety/tool/auth.py
  safety/tool/pip/main.py
  safety/tool/uv/command.py
  tests/tool/test_auth.py
  tests/tool/uv/test_uv_command.py
Labels: bug

#753 chore: update CHANGELOG.md with note
  CHANGELOG.md
Labels: enhancement

#754 fix: missing poetry index credentials
  safety/constants.py
  safety/tool/poetry/command.py
  tests/tool/__init__.py
  tests/tool/base.py
  tests/tool/poetry/__init__.py
  tests/tool/poetry/test_poetry_command.py
  tests/tool/uv/__init__.py
  tests/tool/uv/test_uv_command.py
Labels: bug

#755 chore: add retries to legacy requests
  safety/auth/utils.py
  safety/safety.py
  tests/test_safety.py
Labels: enhancement
